name: CI - PULL REQUEST ON DEVELOPMENT

on:
  pull_request:
    branches:
      - Development

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install dependencies
        run: npm install

      - name: install libXscrnSaver
        run: sudo yum -y install libXScrnSaver-1.2.2-6.1.el7.x86_64

      - name: run build
        run: npm run build

      - name: Run test
        env:
          CI: true
          VITE_PREVIEW_URL: https://localhost:3000/
          VITE_HEADLESS: new
        run: npm run test

