name: CI - PULL REQUEST ON DEVELOPMENT

on:
  pull_request:
    branches:
      - Development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          cache: 'npm'
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      
      - name: Install dependencies
        run: npm install

      - name: Perform e2e tests with Heaful Puppeteer
        uses: maufrontier/puppeteer-headful@v3
        env:
          VITE_HEADLESS: 'false'

        with:
          commands: |
            npm run build
            npm run test

