name: CI - PULL REQUEST ON DEVELOPMENT

on:
  pull_request:
    branches:
      - Development

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install dependencies
        run: npm install

      - name: run build
        run: npm run build

      - name: Test Menu
        run: npm run test Menu.e2e.test.js

      - name: Test MenuOrders
        run: npm run test MenuOrders.e2e.test.js

      - name: Test Orders
        run: npm run test Orders

      - name: Test Utils
        run: npm run test Utils
